name: Test GHA bug

on:
  workflow_dispatch:

env:
  MY_ENV_VAR: foo

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Mona it's Monday"
        if: env.MY_ENV_VAR == 'foo'
        run: echo "no-greeting no-name. Today is whatever"
        
  what-works:
    if: env.MY_ENV_VAR == 'foo'
    runs-on: [ubuntu-latest]

    steps:
      - run: |
          echo "Foo is foo"

  what-doesnt-work:
    if: startsWith('foobar', env.MY_ENV-VAR)
    runs-on: [ubuntu-latest]

    steps:
      - run: |
          echo "Never get to tell that foobar startsWith foo"
